name: mirrorchyan_release

on:
  workflow_dispatch:

jobs:
  mirrorchyan_release:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os: [win, macos, linux]
        arch: [aarch64, x86_64]
        exclude:
          - os: win
            arch: aarch64
    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "MAA_MHXY_SK-${{ matrix.os }}-${{ matrix.arch }}-*"
          mirrorchyan_rid: MAA_MHXY_SK

          owner: Diaoff
          repo: Maa_MHXY_SK
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}
